-- MySQL Script generated by MySQL Workbench
-- 03/16/17 22:42:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nomnom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nomnom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nomnom` DEFAULT CHARACTER SET utf8 ;
USE `nomnom` ;

-- -----------------------------------------------------
-- Table `nomnom`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`products` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`recipes` (
  `recipe_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(800) NOT NULL,
  `duration` INT(11) NOT NULL,
  `difficulty` INT(11) NOT NULL,
  `rating` INT(11) NOT NULL,
  `food_type` INT(11) NOT NULL,
  PRIMARY KEY (`recipe_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`recipes_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`recipes_has_products` (
  `recipes_recipe_id` INT(11) NOT NULL,
  `products_product_id` INT(11) NOT NULL,
  PRIMARY KEY (`recipes_recipe_id`, `products_product_id`),
  INDEX `fk_recipes_has_products_products1_idx` (`products_product_id` ASC),
  INDEX `fk_recipes_has_products_recipes1_idx` (`recipes_recipe_id` ASC),
  CONSTRAINT `fk_recipes_has_products_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `nomnom`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_products_recipes1`
    FOREIGN KEY (`recipes_recipe_id`)
    REFERENCES `nomnom`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`users` (
  `users_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rang` INT(11) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`users_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`users_has_products` (
  `users_users_id` INT(11) NOT NULL,
  `products_product_id` INT(11) NOT NULL,
  PRIMARY KEY (`users_users_id`, `products_product_id`),
  INDEX `fk_users_has_products_products1_idx` (`products_product_id` ASC),
  INDEX `fk_users_has_products_users1_idx` (`users_users_id` ASC),
  CONSTRAINT `fk_users_has_products_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `nomnom`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_products_users1`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `nomnom`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`users_has_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`users_has_recipes` (
  `users_users_id` INT(11) NOT NULL,
  `recipes_recipe_id` INT(11) NOT NULL,
  `recipeType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_users_id`, `recipes_recipe_id`),
  INDEX `fk_users_has_recipes_recipes1_idx` (`recipes_recipe_id` ASC),
  INDEX `fk_users_has_recipes_users_idx` (`users_users_id` ASC),
  CONSTRAINT `fk_users_has_recipes_recipes1`
    FOREIGN KEY (`recipes_recipe_id`)
    REFERENCES `nomnom`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_recipes_users`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `nomnom`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nomnom`.`users_rated_recipes1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nomnom`.`users_rated_recipes1` (
  `users_users_id` INT(11) NOT NULL,
  `recipes_recipe_id` INT(11) NOT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`users_users_id`, `recipes_recipe_id`),
  INDEX `fk_users_has_recipes1_recipes1_idx` (`recipes_recipe_id` ASC),
  INDEX `fk_users_has_recipes1_users1_idx` (`users_users_id` ASC),
  CONSTRAINT `fk_users_has_recipes1_recipes1`
    FOREIGN KEY (`recipes_recipe_id`)
    REFERENCES `nomnom`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_recipes1_users1`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `nomnom`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
